export AZP_URL='https://dev.azure.com/Leidos-Eglin/'
export AZP_TOKEN='EXYyV8DkgpKa5fF4jfQqeUWiuIwA6Ob9O8ToN1pJqY7OrLCYgzeAJQQJ99ALACAAAAAAAAAAAAASAZDO02Pk'
export AZP_POOL='Default'
export AZP_AGENT_VERSION='3.243.1'
export AGENT_ALLOW_RUNASROOT=0